# lyne help - Show available commands

echo "lyne - Dotfiles management CLI"
echo ""
echo "Usage: lyne <command> [args...]"
echo ""
echo "Commands:"
echo "  state       Manage state.json"
echo "  theme       Manage theme mode and presets"
echo "  migrate     Manage migration scripts"
echo "  update      Pull latest changes, sync state and run migrations"
echo "  git         Run git commands in the dotfiles repo"
echo "  reload      Reload QuickShell"
echo "  workspaces  Show each monitor's workspace blocks"
echo "  monitors    Monitor rules from Settings; revert a trial, or reset them"
echo "  autostart   Show what starts at login"
echo "  keyboard    Show keyboard layouts, options and per-keyboard layouts"
echo "  gpu         Show the graphics cards; the order Hyprland uses them in"
echo "  nvidia      NVIDIA driver status; install or fix the driver"
echo "  zen         Zen Browser profiles that follow the shell theme"
echo "  help        Show this help message"
echo ""
echo "Run 'lyne <command> --help' for more information on a command."
